#!/bin/bash
set -euo pipefail

# Configuration
ZIP_DIR="."
OUTPUT_DIR="dist"

# Clean up previous build
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Create a temporary directory for unzipped projects
TEMP_UNZIP_DIR=$(mktemp -d)
echo "Temporary unzip directory: $TEMP_UNZIP_DIR"

# Find all zip files in the root (excluding subdirectories to avoid infinite loops or re-processing)
# and sort them alphabetically.
mapfile -d '' ZIP_FILES < <(find "$ZIP_DIR" -maxdepth 1 -type f -name "*.zip" -print0 | sort -z)
NUM_ZIP_FILES=${#ZIP_FILES[@]}

if [ "$NUM_ZIP_FILES" -eq 0 ]; then
    echo "No zip files found in $ZIP_DIR. Exiting."
    exit 1
fi

echo "Found $NUM_ZIP_FILES zip files: ${ZIP_FILES[@]}"

HOMEPAGE_LINKS=""
SITE_COUNT=0
SUCCESSFUL_BUILDS=0

cleanup() {
    echo "Cleaning up temporary directory: $TEMP_UNZIP_DIR"
    rm -rf "$TEMP_UNZIP_DIR"
}
trap cleanup EXIT

for ZIP_FILE in "${ZIP_FILES[@]}"; do
    SITE_COUNT=$((SITE_COUNT + 1))
    SITE_NAME="$SITE_COUNT"
    UNZIP_PATH="$TEMP_UNZIP_DIR/$SITE_NAME"
    FINAL_SITE_PATH="$OUTPUT_DIR/$SITE_NAME"

    echo "----------------------------------------"
    echo "Processing $(basename "$ZIP_FILE") as Site #$SITE_NAME..."

    # Unzip the project
    mkdir -p "$UNZIP_PATH"
    unzip -q "$ZIP_FILE" -d "$UNZIP_PATH"

    # Find the actual project root (where package.json is)
    # Search up to 2 levels deep in case of nested folders in zip
    PACKAGE_JSON_PATH=$(find "$UNZIP_PATH" -maxdepth 2 -name "package.json" | head -n 1)

    if [ -z "$PACKAGE_JSON_PATH" ]; then
        echo "Warning: package.json not found in $ZIP_FILE. Skipping."
        continue
    fi

    BUILD_PATH=$(dirname "$PACKAGE_JSON_PATH")
    echo "Building project in $BUILD_PATH"

    # Build the Vite-React project
    # Using --if-present to handle cases where build script might be named differently
    if [ -f "$BUILD_PATH/package-lock.json" ]; then
        (cd "$BUILD_PATH" && npm ci && npm run build --if-present)
    else
        (cd "$BUILD_PATH" && npm install && npm run build --if-present)
    fi

    # Check if build produced a dist folder
    if [ -d "$BUILD_PATH/dist" ]; then
        mkdir -p "$FINAL_SITE_PATH"
        cp -a "$BUILD_PATH/dist/." "$FINAL_SITE_PATH/"
        HOMEPAGE_LINKS+="$(printf '<li><a href="%s/index.html">Website %s</a></li>\n' "$SITE_NAME" "$SITE_NAME")"
        SUCCESSFUL_BUILDS=$((SUCCESSFUL_BUILDS + 1))
        echo "Successfully built and moved $ZIP_FILE to $FINAL_SITE_PATH"
    else
        echo "Error: Build did not produce a 'dist' directory in $BUILD_PATH"
    fi
done

if [ "$SUCCESSFUL_BUILDS" -eq 0 ]; then
    echo "No sites were built successfully."
    exit 1
fi

# Generate homepage
echo "----------------------------------------"
echo "Generating homepage..."
cat << EOT > "$OUTPUT_DIR/index.html"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Websites Collection</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 40px; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; }
        h1 { border-bottom: 2px solid #eee; padding-bottom: 10px; }
        ul { list-style: none; padding: 0; }
        li { margin: 10px 0; padding: 15px; background: #f9f9f9; border-radius: 8px; border: 1px solid #eee; transition: transform 0.2s; }
        li:hover { transform: translateX(5px); background: #f0f7ff; border-color: #007bff; }
        a { text-decoration: none; color: #007bff; font-weight: bold; display: block; }
    </style>
</head>
<body>
    <h1>My Websites Collection</h1>
    <p>Automatically deployed collection of Vite-React projects.</p>
    <ul>
        $HOMEPAGE_LINKS
    </ul>
    <footer style="margin-top: 50px; font-size: 0.8em; color: #888;">
        Generated by GitHub Actions
    </footer>
</body>
</html>
EOT

echo "Homepage generated in $OUTPUT_DIR/index.html"
echo "Done!"
